ebook/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', include('pickabook.urls')),
    path('accounts/', include('accounts.urls')),
    path('pickabook/', include('pickabook.urls')),
    path('admins/', include('admins.urls')),
    path('pickabook/', include('frontend.urls')),
    # path('quiz/', include('Quiz.urls'))
]

frontend/urls.py
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('home', views.homepage, name='my_homepage'),
    path('quotes', views.show_quotes),
    path('explore', views.all_books),
    path('recommend/<int:pk>', views.recommend),
    path('genres', views.show_categories),
    path('books/<int:category_id>', views.show_books ),
    path('book', views.book_detail),
    path('news', views.show_news)
]

frontend/models.py
from django.db import models

# Create your models here.

pickabook/models.py
from django.contrib.auth.models import User
from django.db import models
from django.core.validators import *
from django.core import validators


class Quotes(models.Model):
    objects = None
    quote_description = models.TextField(null=True)
    quote_author= models.CharField(max_length=500, null=True, validators=[validators.MinLengthValidator(2)])
    created_date = models.DateTimeField(auto_now_add=True, null=True)

    def __str__(self):
        return self.quote_description


class Category(models.Model):
    category_name=models.CharField(max_length=200, null=True, validators=[validators.MinLengthValidator(2)])
    category_description= models.TextField()
    created_date= models.DateTimeField(auto_now_add=True, null=True)

    def __str__(self):
        return self.category_name


class Books(models.Model):
    objects = None
    book_title = models.CharField(max_length=500, null=True)
    book_image = models.ImageField(upload_to='static/uploads', null=True)
    book_pdf = models.FileField(upload_to='static/uploads', null=True)
    created_date = models.DateTimeField(auto_now_add=True, null=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.Book_title



class Book_detail(models.Model):
    objects = None
    book = models.ForeignKey(Books, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.Book_ID


class News(models.Model):
    objects = None
    title = models.CharField(max_length=500, null=True)
    image = models.ImageField(upload_to='static/uploads', null=True)
    video = models.FileField(upload_to='static/uploads', null=True)
    description= models.TextField()
    created_date = models.DateTimeField(auto_now_add=True, null=True)

    def __str__(self):
        return self.title




frontend/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect

from accounts.auth import user_only
from pickabook.models import Quotes, Category, Books, News


@login_required
@user_only
def homepage(request):
    context = {
        'activate_homepage': 'active'
    }
    return render(request, 'frontend/homepage.html', context)


def show_quotes(request):
    quotes = Quotes.objects.all().order_by('-id')
    context={
        'quotes': quotes,
        'activate_quotes_user': 'active'
    }
    return render(request, 'frontend/show_quotes.html', context)


def show_categories(request):
    categories= Category.objects.all().order_by('-id')
    context={
        'categories':categories,
        'activate_category': 'active'
    }
    return render(request, 'frontend/show_categories.html', context)


def show_books(request, category_id):
    category = Category.objects.get(id=category_id)
    context = {
        'category': category,
        'activate_book': 'active'
    }
    return render(request, 'frontend/show_books.html', context)


def all_books(request):
    book = Books.objects.all().order_by('-id')
    context = {
        'book': book,
        'activate_book': 'active'
    }
    return render(request, 'frontend/all_books.html', context)


def recommend(request, pk):
    book = Books.objects.get(pk=6)
    context = {
        'book': book,
        'activate_book': 'active'
    }
    return render(request, 'frontend/all_books.html', context)


def book_detail(request, ):
    book = Books.objects.get
    context = {
        'book': book,
        'activate_book_detail': 'active'
    }
    return render(request, 'frontend/book_detail.html', context)


def show_news(request):
    news = News.objects.all().order_by('-id')
    context = {
        'news': news,
        'activate_news': 'active'
    }
    return render(request, 'frontend/show_news.html', context)




frontend/templates/frontend/all_books.html
{% extends 'layout.html' %}
{% load static %}

{% block title %}
<title>Explore</title>
{% endblock title %}

{% block main_content %}
<div class="arrow">
  <a href=""><i class="fa fa-angle-up text-light" aria-hidden="true"></i></a>
 <span class="arr">Go to top</span>
</div>

<nav aria-label="breadcrumb" class="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="/homepage">Home</a></li>
    <li class="breadcrumb-item active" aria-current="page">All books</li>
  </ol>
</nav>
<div class="container py-3">
    <div class="row justify-content-around">
        {% for i in book %}
        <div class="row ">
        <div class="best-books col-md-3 col-sm-3">
          <div class="card" style="width: 16rem; ">
            <div class="img">
              <img src="/{{i.book_image}}" class="card-img-top" alt="...">
            </div>
            <div class="card-body">
              <p class="card-title fw-bold fs-5">{{i.book_title}}</p>
              <p class="card-text">authors name</p>

            </div>
            <div class="best-hover text-center">
              <a href="/pickabook/book/{{i.id}}" class="pb-3 {{activate_book_detail}}">View Details <i class="fa fa-arrow-right" aria-hidden="true"></i></a>
              <a href="#"><i class="fa fa-heart-o" aria-hidden="true"></i></a>
              <a href="#" class="py-3">Download </a>
            </div>
          </div>

        </div>

    </div>
        {% endfor %}
         </div>
    </div>
</div>






{% endblock main_content %}

frontend/templates/frontend/show_books.html
<style>
.image_zoom{
transition: transform .2s;
padding:10px;
}
.image_zoom:hover{
transform: scale(1.3);
overflow:hidden;
}

.card-top{
overflow:hidden;
}

</style>

{% extends 'layout.html' %}
{% load static %}
{% block title %}

<title>News</title>
{% endblock title %}

{% block main_content %}
<div class="arrow">
  <a href=""><i class="fa fa-angle-up text-light" aria-hidden="true"></i></a>
 <span class="arr">Go to top</span>
</div>

        {% include 'messages.html' %}
        {% for i in category.books_set.all  %}
<nav aria-label="breadcrumb mx-5" class="breadcrumb">
    <ol class="breadcrumb mx-5">
      <li class="breadcrumb-item"><a href="homepage_login.html">Home</a></li>
      <li class="breadcrumb-item"><a href="genre.html">Genre</a></li>
      <li class="breadcrumb-item active" aria-current="page">{{i.category.category_name}}</li>
    </ol>
  </nav>


<!--<div class="container">-->
<!--    <div class="row justify-content-around shadow-lg">-->

<!--        <div class="card col-md-8 m-2 card-top">-->
<!--            <div class="card-body">-->
<!--                <h2 class="card-title">{{i.book_title}}</h2>-->
<!--                <div class="" style="overflow:hidden;">-->
<!--                    <img src="/{{i.book_image}}" class="card-img-top image_zoom" alt="..." >-->
<!--                </div>-->
<!--&lt;!&ndash;                <h5 class="card-text">{{i.news_description}}</h5>&ndash;&gt;-->
<!--                 <p class="card-text">{{i.category.category_name}}</p>-->
<!--                <a href="/news/add_to_favourite/{{i.id}}" class="btn btn-primary"-->
<!--                    onclick="return confirm('Are you sure want to add this item to favourites?')">Add to Favourites</a>-->
<!--            </div>-->


<!--        </div>-->
        <section id="recommendation" class="allbooks">
  <div class="container py-3 ">
      <div class="title text-center">
          <h4 class="fs-1 pb-5"> <span>{{i.category.category_name}}</span></h4>
      </div>
      <div class="row ">
        <div class="best-books col-md-3 col-sm-3">
          <div class="card" style="width: 16rem; ">
            <div class="img">
              <img src="images/book4.jpg" class="card-img-top" alt="...">
            </div>
            <div class="card-body">
              <p class="card-title fw-bold fs-5">{{i.book_title}}</p>
              <p class="card-text">authors name</p>

            </div>
            <div class="best-hover text-center">
              <a href="/pickabook/book/{{i.id}}" class="pb-3 {{activate_book_detail}}">View Details <i class="fa fa-arrow-right" aria-hidden="true"></i></a>
              <a href="#"><i class="fa fa-heart-o" aria-hidden="true"></i></a>
              <a href="#" class="py-3">Download </a>
            </div>
          </div>

        </div>

    </div>
    <nav aria-label="Page navigation example" class="py-4">
      <ul class="pagination justify-content-end me-5">
        <li class="page-item">
          <a class="page-link" href="#" aria-label="Previous">
            <span aria-hidden="true">&laquo;</span>
          </a>
        </li>
        <li class="page-item"><a class="page-link" href="#">1</a></li>
        <li class="page-item"><a class="page-link" href="#">2</a></li>
        <li class="page-item"><a class="page-link" href="#">3</a></li>
        <li class="page-item">
          <a class="page-link" href="#" aria-label="Next">
            <span aria-hidden="true">&raquo;</span>
          </a>
        </li>
      </ul>
    </nav>

  </div>
</section>

        {% endfor %}

<!--    </div>-->
<!--</div>-->

{% endblock main_content %}

frontend/templates/frontend/show_categories.html
{% extends 'layout.html' %}
{% load static %}

{% block title %}
<title>Genres</title>
{% endblock title %}

{% block main_content %}
<div class="arrow">
  <a href=""><i class="fa fa-angle-up text-light" aria-hidden="true"></i></a>
 <span class="arr">Go to top</span>
</div>

<nav aria-label="breadcrumb" class="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="/homepage">Home</a></li>
    <li class="breadcrumb-item active" aria-current="page">Genre</li>
  </ol>
</nav>
<!--<div class="container">-->
<!--    <div class="row justify-content-around">-->
<!--        {% for i in categories %}-->
<!--        <div class="card col-md-8 shadow m-3">-->

<!--            <div class="card-body">-->
<!--                <h1 class="card-title" style="color:orange">{{i.category_name}}</h1>-->
<!--                <h4 class="card-text">{{i.category_description}}</h4>-->
<!--                <a class="nav-link {{activate_book}} " href="/pickabook/books/{{i.id}}" style="font-size:20px;" >View Books</a>-->
<!--            </div>-->
<!--        </div>-->

<!--        {% endfor %}-->
<!--    </div>-->
<!--</div>-->
<!--    </div>-->

<section id="art-design">
  <div class="art">
    <div class="container ">
        {% for i in categories %}
        <div class="title text-start ">
            <h4 class="fs-1"><span>{{i.category_name}}</span></h4>
              <a   href="/pickabook/books/{{i.id}}" class="fs-5 me-5 pt-3 view-all float-end {{activate_book}}">View all <i class="fa fa-arrow-right" aria-hidden="true"></i></a>
        </div>
        {% endfor %}

        <div id="owl-demo3" class="owl-carousel owl-theme">
            {% for i in category.books_set.all  %}
            <div class="item">
              <div class="img">
                <img src="/{{i.book_image}}" class="card-img-top image_zoom" alt="..." >

                <div class="best-click text-center ">
                  <a href="#" class="pb-3">View Details <i class="fa fa-arrow-right" aria-hidden="true"></i></a>
                  <a href="#"><i class="fa fa-heart-o" aria-hidden="true"></i></a>
                  <a href="#" class="py-3">Download </a>

              </div>
            </div>
                <div class="latest-content mt-2">
                  <span class="author fs-6">John Strass</span><br>
                  <span class=" book fs-5 fw-bold "> Summer Times Love Stories</span><br>
                  <span class=" price fs-5">$20.00</span>
                </div>
              </div>
            {% endfor %}
          </div>

    </div>
  </div>
  </section>





{% endblock main_content %}

frontend/templates/frontend/show_news.html
{% extends 'layout.html' %}
{% block title %}
<title>News & Interviews </title>
{% endblock%}
{% block main_content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-10 offset-md-1">
            <h1 class="text-center">News and Interviews</h1>
            {% include 'messages.html' %}
            <div class="card py-2 px-2 m-5 shadow-lg">
                <div class="card-body">
                    {% for i in news %}
                    <h1>{{ i.title }} </h1>
                    <div class="img">
                        <img src="/{{i.image}}" class="card-img-top" alt="...">
                    </div>

                        <h6> {{ i.description }}</h6>
                    <h6> {{ i.created_date }} </h6>
                </div>
                </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

frontend/templates/frontend/show_quotes.html
{% extends 'layout.html' %}
{% load static %}

{% block title %}
<title>Quotes</title>
{% endblock title %}

{% block main_content %}
<section id="quotes">
    <div class="container quotes">
        <div class="title text-center">
            <h4 class="fs-1 pb-3 pt-2">Popular <span>Quotes</span></h4>
            <form class="d-flex search justify-content-end mb-5">
                <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success" type="submit"><i class="fa fa-search" aria-hidden="true"></i></button>
              </form>
        </div>
        <div class="quotes-content">
            {% for i in quotes %}
            <div class="row py-4 justify-content-center">
            <div class="col-md-2">
                <img src="{% static 'images/a1.jpg' %}" alt="">

            </div>
            <div class="col-md-5">
                <p>"{{i.quote_description}} "</p>
                <span><a>"{{i.quote_author}}" </a></span>
            </div>
            <div class="col-md-1">
                <a href="#" class="btn btn-primary" id="change" onclick="changeColor()">Like <i class="fa fa-thumbs-o-up" aria-hidden="true"></i></a>
            </div>
        </div>

            {% endfor %}
        </div>
    </div>
</section>

{% endblock main_content %}